### ISSUE TITLE
"Let's make music" is not the correct name.

### ISSUE THREAD

**Issue by alugarius** [LewisVo/Awesome-Linux-Software#130]
It's just "LMMS" or "Linux MultiMedia Studio"

**Comment by alugarius** [comment]
It's also open source

**Comment by LewisVo** [comment]
Sorry. The last time I check I couldn't find a link to the source code. Also, I dont invent the name. Let's make music is right on their home site and I have no idea whether it is Linux MultiMedia Studio. https://lmms.io

**Comment by LewisVo** [comment]
Fixed both.

**Comment by alugarius** [comment]
The official name is just LMMS, 
https://github.com/LMMS/lmms

Wikipedia is also kinda helpful
"LMMS (formerly Linux MultiMedia Studio) is digital audio workstation software. "

**Comment by alugarius** [comment]
Thanks, I will look a little closer some time
