### ISSUE TITLE
mockingbot-a prototying design tool

### ISSUE THREAD

**Issue by levinit** [LewisVo/Awesome-Linux-Software#135]
[MockingBot-Mobile Prototyping & Collaboration without Headaches](https://modao.cc/)
It provides,
- Desktop:Win/MacOS/Linux(only provide [deb package](https://modao.cc/downloads),unpack the deb ,you can find the sourcecode).
I have make a aur ([mockingbot](https://aur.archlinux.org/packages/mockingbot/)) package for archlinux user
- Mobile(syncing and preview):IOS/Android
- sketch plugin

**Comment by levinit** [comment]
[catfish](https://launchpad.net/catfish-search)
Versatile file searching tool

**Comment by levinit** [comment]
[firewalld](https://github.com/firewalld/firewalld)
  Firewall daemon with D-Bus interface

**Comment by LewisVo** [comment]
Hi @levinit , I have already checked out MockingBot. However, I find that the tutorial page is still in Chinese. Could you find a tutorial anywhere else that has an English version ?

**Comment by levinit** [comment]
@LewisVo I am sorry,I pasted a wrong url,"modao.cc" is for Chinese，international site is [https://mockingbot.com](https://mockingbot.com).
Here is [turtorial:English-version](https://mockingbot.com/tutorials/345).

**Comment by LewisVo** [comment]
Thank you. I will add this in the next commit. Let's leave this issue open for a while.

**Comment by levinit** [comment]
dev-tool
- [meld](http://meldmerge.org/)-Meld is a visual diff and merge tool targeted at developers. (GUI)
- [diffuse](https://sourceforge.net/projects/diffuse/) - Diffuse is a graphical tool for comparing and merging text files. It can retrieve files for comparison from Bazaar, CVS, Darcs, Git, Mercurial, Monotone, RCS, Subversion, and SVK repositories.(GUI)

**Comment by levinit** [comment]
[pb-for-desktop](https://github.com/sidneys/pb-for-desktop) - PB for Desktop is a lightweight open-source Desktop app for PushBullet.  (nice app)

**Comment by LewisVo** [comment]
Such great suggestions! Thank you. 💌

**Comment by levinit** [comment]
video
[clipgrab](https://clipgrab.org/)      A friendly downloader for YouTube and other sites.
[popcorntime](https://www.popcorn-time.to/)     a cross platform opensource program.support win/osx/linux/ios/android.Stream movies from torrents. Skip the downloads.

**Comment by LewisVo** [comment]
Hi @levinit , sorry for keeping you waiting. 7d3472f   All your suggestions have been added ;)
