### ISSUE TITLE
Webstorm and other Jetbrains IDE's?

### ISSUE THREAD

**Issue by benwinding** [LewisVo/Awesome-Linux-Software#155]
Please consider adding Webstorm and other obscure IDE's from Jetbrains?
They work beautifully on Ubuntu, (probably other linux systems too).
Although they are commercial applications, they are high quality and **free for students**... who are probably most likely to come across this list.

**Comment by LewisVo** [comment]
Hi @benwinding, thank you for your opinion. Some Jetbrains' IDE have been included already like IntelliJIdea and Pycharm. I dont mind if they are commercial (this list is not only limited to open source/ free applications anyway). About Webstorm, I ll try to add it soon. ;) we cant know everything existing out there :<

**Comment by benwinding** [comment]
Thanks man, 

Only mentioned it, as Webstorm is one of the reasons I use Linux in development (I'm a student though, what do I know)

Thanks so much for making/maintaining this list!
👍

**Comment by LewisVo** [comment]
@benwinding d44a5b5 You're welcome. I am very glad that this list actually help people.
