### ISSUE TITLE
The use of the dollar sign inside a "forbiden" sign is misleading

### ISSUE THREAD

**Issue by felipesanches** [LewisVo/Awesome-Linux-Software#175]
While I think I understand that the goal was to convey the idea of "gratis", this symbol is also notoriously associated with the idea of "non-commercial". And that's completely opposite to both Free Software and Open Source definitions.

I'd suggest using the actual word "gratis", or, even better, not displaying anything at all (since the gratis aspect is just a detail in comparison to the much broader impact of the ideals of software freedom).

**Comment by LewisVo** [comment]
hi @felipesanches , I totally understand your idea. In fact, a year ago when I made this list, I have the same concern about how to display the "gratis" characteristic of many softwares. So I try to take a look at how others have expressed their ideas and found 2 others awesome lists on different platform that seems to opt for the same icon :   
- https://github.com/Awesome-Windows/Awesome  
- https://github.com/iCHAIT/awesome-macOS  
At this point I assume that the icon is widely known in the community for expressing the "gratis" characteristic. Hence I use it.

**Comment by felipesanches** [comment]
Well... The Creative Commons project is also (and maybe more) widespread. And their widely known use of the symbol carries the idea of "commercial usage is forbidden".

Take a look here, for instance: https://creativecommons.org/licenses/by-nc/4.0/

**Comment by LewisVo** [comment]
Yeah I understand. Thank you for that link, it was very helpful. However, right now I am still not convinced enough to remove the icon. In fact, I don't think replacing it with the word gratis is the best option. Deleting it completely would present a lack of information, which a lot of users may find helpful. I am in the search for another icon. If you have any suggestions, feel free to leave a comment here. Thank you for a very constructive issue.

**Comment by felipesanches** [comment]
Cool! You're welcome :-)

I'm happy to hear that you're looking for a replacement for the icon. Indeed, not doing anything would be the most damaging choice here, since the current state likely conveys a misleading meaning.

Unfortunately, I am not aware of a widespread icon for "gratis", that's why I suggested using the actual word or nothing at all.

**Comment by felipesanches** [comment]
Maybe this could be insightful reading in case you have not seen it yet:
https://www.gnu.org/philosophy/

And there's also this one: https://opensource.org/osd

**Comment by LewisVo** [comment]
Thank you, I have read them both since the day I say bye bye to Windows and switch to Linux. Having worked with the open source community for a long time, I totally understand the philosophy of free/ open source software. In the early days, I was so so imbued with the philosophy that I want to make this list without the inclusion of any non-free ( as in both freedom and free beer). But later on, I find it harsh these days and to be honest, we need to recognize some good commercial softwares that excel at what they do while still offering user a chance to pay nothing at all. 
Anyway, that icon stuff, I am still considering a replacement for sure. But that's gonna take a while ;)

**Comment by felipesanches** [comment]
I politely (but strongly) disagree on the strategy of promoting non-free programs. But I'm not the one running this repo, so... you're the one to decide here.

**Comment by LewisVo** [comment]
I totally understand you. I have no problem with that. I am deciding here but this is the open source world where you can start a fork and remove all the thing that you disagree 😄 , right ? I just want to express my view so that we can understand each other better.

**Comment by LewisVo** [comment]
after 2 days searching, I cannot found an alternative icon that is not only as straightforward as the icon we are using but also easy to view at 12px * 12px. The only icon that I found reasonable is this: https://www.flaticon.com/free-icon/check-mark-in-a-circle_70333#term=free&page=4&position=71 
![image](https://user-images.githubusercontent.com/15828926/29716867-449be46e-89d7-11e7-8ad4-e89bffa4fe93.png)
It is not so... straightforward ( in my opinion ) but err... it works. I don't know... 
![](http://imgur.com/r3000rMl.png)
What do you think ?

**Comment by mikaello** [comment]
I agree with @felipesabino. I just visited this list and immediately recognized ![Freeware](https://camo.githubusercontent.com/26818f2e2c99cbbac8a93f238a9760b68178cfe7/68747470733a2f2f63646e2e7261776769742e636f6d2f6943484149542f617765736f6d652d6f73782f6d61737465722f6d656469612f667265652e737667) as the CC "non-commercial" symbol (<img src="https://user-images.githubusercontent.com/2505178/29740153-f7aae690-8a4f-11e7-9418-9b657c76e6b9.png" width="15px"/>), and the lack of explanation of the symbol was also confusing.

I think that removing it for gratis software, and rather mark the software that is **not gratis** with a different icon would be better.

**Comment by felipesanches** [comment]
I agree with @mikaello 's suggestion.

**Comment by LewisVo** [comment]
Ok, that sounds like a good idea. Will try 👍

**Comment by LewisVo** [comment]
Hi I fix this with 80a5cfd66ecd01a264228756cf62281fc75c708a. Can you take a look back in the list and see if I can close this issue?

**Comment by mikaello** [comment]
Good work! In my opinion this looks much better.
