### ISSUE TITLE
Some descriptions are very subjective

### ISSUE THREAD

**Issue by Calinou** [LewisVo/Awesome-Linux-Software#181]
Many of the entry descriptions are very subjective, for example:

> Numix Icon Theme - One of the best icon theme for ubuntu linux
> uGet - The best download manager for linux.

They probably should be adjusted to be more objective about the software's qualities.

**Comment by LewisVo** [comment]
> Numix Icon Theme - One of the best icon theme for ubuntu linux  

It's my fault. At that time I don't know some good ways to describe a theme pack so I just leave it like that.  

> uGet - The best download manager for linux. 

![image](https://user-images.githubusercontent.com/15828926/29710810-34f2bf62-89bc-11e7-9fa0-9d0644394373.png)

**Comment by Calinou** [comment]
It is indeed the official description of uGet, but I guess briefly mentioning the software's key features would be more useful to readers, as a "best download manager" doesn't tell much about the software.

**Comment by LewisVo** [comment]
I ll leave this open and try to fix them. Thank you :smile:

**Comment by LewisVo** [comment]
With recent updates, I believe that this has been solved. Thank you @Calinou
