### ISSUE TITLE
SIP clients

### ISSUE THREAD

**Issue by dhpowrhost** [LewisVo/Awesome-Linux-Software#194]
Would be nice with a SIP clients category :)

**Comment by LewisVo** [comment]
Hi @dhpowrhost, thank you for visiting the list and suggest some ideas :smile:. Sorry for the lack of SIP clients because I don't have much experience with them and I can't write about anything I don't know or haven't tried. I will try to do some research and until I reach some good resources, I will leave this issue opened. :smiley:

**Comment by dhpowrhost** [comment]
There is a lot of clients:
Blink
Linphone
Ring
Jitsi
Ekiga

**Comment by LewisVo** [comment]
It turns out 

> SIP is an industry standard method of achieving VoIP.

Do you think we really need a separate category for this?

**Comment by dhpowrhost** [comment]
Could be a VoIP category.

**Comment by LewisVo** [comment]
can you suggest a way to split up the chat clients category? Right now some application supports both voip call as well as IM and other things.

**Comment by dhpowrhost** [comment]
I don't think it should be split up. 
IMO you need two categories. Chat clients and VoIP client. Each containing clients including both features.

**Comment by LewisVo** [comment]
That  would cause some redundant repitition

**Comment by dhpowrhost** [comment]
Cant exactly see that as an issue :)

**Comment by LewisVo** [comment]
Yes it does. I never wanted any repitition that makes the list unnecessary longer. :( Maybe i ll think of some ways to achieve this, but not repitition.

**Comment by dhpowrhost** [comment]
IMO usefullness values higher than the perfect structural form. Right now you are leaving out a valuable category because it will contain applications that will be listed in two categories, simply because the fit in both. I guess i can always fork it :)

**Comment by LewisVo** [comment]
@dhpowrhost :+1: yes a fork would serve us both better.

**Comment by LewisVo** [comment]
After a look back, I realize that almost all of the applications in the chat clients have a calling functionality (via VOIP i suppose). Therefore, I decided not to make a separate department for SIP/VOIP, but instead split it up like this 7a19c8f . Thank you for your opinion :+1:
