### ISSUE TITLE
keep this list awesome

### ISSUE THREAD

**Issue by azzamsa** [LewisVo/Awesome-Linux-Software#201]
I would suggest everyone to put only the application in every section, that he like most or favorite, so this list always consist of awesome applications.

**Comment by LewisVo** [comment]
Thank you for your idea, azzamsa. Personally, I think every app has its own quality and audience 😄 but it is good that people put their favorite here and tell there story like you did in your pull request.

**Comment by azzamsa** [comment]
Yes, thank you :).

I recommend this way, because I think that, if someone puts a lot of apps, even though the app is not he use, he put it just because he knows it, without any experience with the app, it certainly will reduce the quality of this list, and it will be very big .

My hope, people come here, can easily choose the app he wants from the section list. because every app on the list really has audience as you say, of course this list will remain consist of awesome software.

**Comment by LewisVo** [comment]
> he put it just because he knows it, without any experience with the app, it certainly will reduce the quality of this list, and it will be very big.   

Which is why I need to run and investigate each pull request 😄 .

> My hope, people come here, can easily choose the app he wants from the section list. because every app on the list really has audience as you say, of course this list will remain consist of awesome software.

So is my hope. 💌

**Comment by azzamsa** [comment]
> Which is why I need to run and investigate each pull request 😄 .

thank you so much for your contribution to community, thank you.

> So is my hope. 💌

:)

**Comment by khomesh24** [comment]
I think we should also add scripts

**Comment by LewisVo** [comment]
Hi @khomesh24 ,  can you elaborate your idea? what do you mean by "scripts"?

**Comment by khomesh24** [comment]
Linux scripts for enabling power line or for installing LEAP stack or LAMP stack.
application that are difficult to install we  can create it's script it might help people.

**Comment by LewisVo** [comment]
@khomesh24  yes thank you. That's a nice idea. In fact in this list, mostly all apps are packaged and easy to install. Some others, if hard to install, I link to a tutorial webpage instead of the homepage of the app. ;)
