### ISSUE TITLE
Placing of icons to the left for improved readability

### ISSUE THREAD

**Issue by felipesanches** [LewisVo/Awesome-Linux-Software#203]
I think the layout of the page would be much more readable if the icons where placed to the left (right in the beginning of each line) since it would make it easier for the reader to quickly navigate with the eyes a vertically aligned sequence of icons, instead of zig-zagging on the current end-of-line icons.

**Comment by LewisVo** [comment]
Hi @felipesabino , thank you for your idea. It sounds sensible, I ll try that 👍

**Comment by felipesabino** [comment]
Hi @LewisVo I guess you meant to `@` @felipesanches instead 😉

**Comment by LewisVo** [comment]
@felipesabino  Sorry, I editted that. Sorry, I was sleepy .. :sob:

**Comment by ivernus** [comment]
Would my commit be a step in the right direction or were you thinking of something else @LewisVo

**Comment by ivernus** [comment]
Thanks for checking @LewisVo , I've created #270 with some notes on the changes

**Comment by LewisVo** [comment]
@felipesanches It's been a long time but icons are now moved to the left. Thank you all.
