### ISSUE TITLE
Gaming additions & restructuring

### ISSUE THREAD

**Issue by XYQuadrat** [LewisVo/Awesome-Linux-Software#204]
The gaming section is currently very unorganized, I would suggest ordering them by genre. Civilizations 5, although a great game, is mainly available through Steam, so you might want to remove it. Here are some additions (I tested most of them):  

RTS
---
1. [Warzone 2100] (https://www.wz2100.net/)
2. [OpenRA] (http://www.openra.net/)
3. [Widelands] (https://wl.widelands.org/)
4. [Globulation 2] (https://globulation2.org/)
5. [FreeCiv] (http://www.freeciv.org/)

City Building Simulation
------------------------
1. [Unknown Horizons] (http://unknown-horizons.org/)
2. [FreeCol] (http://www.freecol.org/)

FPS
---
1. [Unreal Tournament] (https://www.unrealtournament.com/)
2. [Red Eclipse] (https://redeclipse.net/)
3. [Urban Terror] (http://www.urbanterror.info)
4. [Zandronum] (http://zandronum.com/)

Action
------
1. [King Arthur's Gold] (https://kag2d.com)
2. [Tales of Maj'Eyal] (https://te4.org/)
3. [Zelda Classic] (http://www.zeldaclassic.com/)
4. [Zelda: Mystery of Solarus DX] (http://www.solarus-games.org)

MMORPG
------
1. [Eternal Lands] (http://www.eternal-lands.com)

These are in no particular order or ranking, but all are FOSS. I got some more, but that's it for now.

**Comment by dessalines** [comment]
Why not submit a PR, organizing all the games currently there?

**Comment by azzamsa** [comment]
@XYQuadrat if your restructuring is good, please sumbit a PR.

**Comment by LewisVo** [comment]
@XYQuadrat  your restructuring is very good. Thank you for your idea. I am trying to reorganize many sections into subsections. The game category will be among the first to be noticed 👍

**Comment by LewisVo** [comment]
Closed thanks to  #218
