### ISSUE TITLE
Site offline

### ISSUE THREAD

**Issue by FannyVieira** [LewisVo/Awesome-Linux-Software#206]
LInux Pocket Guide - http://www.opencore.eesc.usp.br/bruno/livros/Linux_Pocket_Guide.pdf

**Comment by LewisVo** [comment]
Hi @FannyVieira , thank you for reporting the dead link. I replace it with 1ef4fc323d38395d5d1e6b7dea0574588ec8a8a7 . I hope you'll find your way to the documents :+1:

**Comment by FannyVieira** [comment]
Yes, I did. Thank you. <3
