### ISSUE TITLE
我才不告诉你我有阿里云优惠券-> http://izhuanyer.top

### ISSUE THREAD

**Issue by MMMzq** [LewisVo/Awesome-Linux-Software#213]

**Comment by vitalkanev** [comment]
Well :scream:
The translation looks like a spam, or even advertising!

**Comment by LewisVo** [comment]
Hi @MMMzq and @vitalkanev , could you describe to me what is going on with the chinese translation? From the title I did try to translate but could not understand the problem 😢 
![image](https://user-images.githubusercontent.com/15828926/29965660-b28336ba-8f38-11e7-9d8c-952c472ddac0.png)

**Comment by hughgrigg** [comment]
This is spam

**Comment by LewisVo** [comment]
Thank you @hughgrigg

**Comment by MMMzq** [comment]
I am embarrassed by my previous behavior, I am very sorry.
