### ISSUE TITLE
Wrong link for wpgtk

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#214]
The link for wpgtk currently given ([https://github.com/LewisVo/github.com/deviantfero/wpgtk](https://github.com/LewisVo/github.com/deviantfero/wpgtk)) doesn't work as it mixes the urls of both this repository and the wpgtk one. The correct url is [https://github.com/deviantfero/wpgtk](https://github.com/deviantfero/wpgtk) or alternatively, for a better presentation, the project's github.io homepage, [http://deviantfero.github.io/wpgtk](http://deviantfero.github.io/wpgtk).
Just thought I'd point out this small mistake so it can be fixed. Thanks in advance for the understanding.

**Comment by LewisVo** [comment]
The link should be https://github.com/deviantfero/wpgtk but the contributor missed the \//. 
Thank you @lmintmate .
