### ISSUE TITLE
Remove the Terminix entry from the list, as it's evolved into Tilix

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#215]
Terminix was the previous name of Tilix. As the Tilix repository states:

> Note that Terminix is changing its name to Tilix due to a trademark issue with the Terminix International Corporation. It may take a few weeks to complete the process, thank you in advance for your patience while we work through this change.

(the change already happened, they just didn't update the message to show they worked through it...)
In addition, the link with blue letters for the Terminix entry shows a 404, and the link from the OSI icon redirects to the Tilix repository. In short, the Terminix entry is redundant, since Tilix is the same thing, only with a different name.
Thanks in advance for understanding.

**Comment by LewisVo** [comment]
Thank you. It's fine. You are doing what's beneficial to the society, #195

**Comment by yernhi** [comment]
Deepin Store provies some orignal softwares (though they are designed for Deepin OS): https://www.deepin.org/en/original/
