### ISSUE TITLE
Graphics -> Video editor: shotcut

### ISSUE THREAD

**Issue by gnanet** [LewisVo/Awesome-Linux-Software#221]
Under [Video editor](https://github.com/LewisVo/Awesome-Linux-Software#video-editor) **Shotcut**  could be a good addition:

[Shotcut](https://www.shotcut.org/)  - cross-platform (Qt), open-source (GPLv3) video editor. Major features include support for a wide range of formats; no import required meaning native timeline editing; extensive list of filters; and resolution support to 4k. [![OSS Icon](https://camo.githubusercontent.com/123c212a73b8dd36e355c193788ea3d8baa36f73/68747470733a2f2f63646e2e7261776769742e636f6d2f6943484149542f617765736f6d652d6f73782f6d61737465722f6d656469612f6f73732e737667) available on github](https://github.com/mltframework/shotcut/)

**Comment by LewisVo** [comment]
Thank yuou @gnanet , I ll try shotcut out  and see if it is possible to add that into the list. Soon. 😄

**Comment by gnanet** [comment]
I suggest to watch the [tutorial videos](https://www.shotcut.org/tutorials/) if you get stuck somewhere, i quickly could find the solutions to any problems i faced. 

This short clip from my summer trip to croatia was made using shotcut: https://content.jwplatform.com/previews/vk6HrqKS-SCjsajGp

**Comment by LewisVo** [comment]
@gnanet , thank you for the link to the tutorial. I have had some times to play with Shotcut and it was amazing.
