### ISSUE TITLE
Infinality Bundle's hompage isn't up anymore

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#223]
#195 
When I clicked on the link to Infinality's homepage ([bohoomil.com](https://bohoomil.com/)), I got redirected to the webpage of some German consultant (at [https://gbconsult.info/](https://gbconsult.info/)). This has apparently been the case for quite a few months, since Web Archive's wayback machine shows the page being last live [on December 13th, 2016](https://web.archive.org/web/20161213223431/https://bohoomil.com/). [The project's repository](https://github.com/bohoomil/fontconfig-ultimate) however is still live. Since the Infinality bundle isn't maintained anymore as the relevant entry already states, you could either completely remove the link to the not-existing anymore hompage, or use the Wayback Machine link instead, or, alternatively, completely remove said project since you are already removing other unmaintained projects - your call.

P.S. As an addendum, I also checked the links present in the (still live) repository, and the arch wiki page is (as expected) dead, saying there is no text on the page. Said page was, [according to the logs](https://wiki.archlinux.org/index.php?title=Special:Log&page=Infinality-bundle%2Bfonts) deleted on January 18th 2017, and hadn't been interacted with since 2014. Same with the AUR page, which shows a 404 error and was last live in August 2015, according again to the Wayback Machine. This in regards to Arch Linux.
Regarding Ubuntu and derivatives, I (using Mint 18.2, based on Ubuntu 16.04) just checked Synaptic to see if Infinity was listed as a package, and it was not, something that reduces both Infinality's visibility and ease of install. Just thought I'd add these additional observations to help you decide what to do in this case.

**Comment by LewisVo** [comment]
HI @lmintmate , thank you for your report.
1.  https://bohoomil.com/ is down right now ( proof : http://downforeveryoneorjustme.com/bohoomil.com ) Also, I am not being redirected as you. It just shows an error page. 
2. You re right, it seems to be down for a long time. 
3. I think I will dump the official link for the link to github :+1:
