### ISSUE TITLE
The OSS icon repository link for Vocal shows a 404.

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#224]
The [repository link at the OSS icon for the Vocal entry](https://github.com/vocalapp) now shows a 404 error. The homepage link still works, but the Github link it gives to the bottom of the page is the same invalid one. By searching on Github for the term "vocal" I found what looks like [the current repository for Vocal](https://github.com/needle-and-thread/vocal), especially as the latest commit there was a mere 2 days ago. The link to this repository could thus replace the previous, not-working one.
Thanks again in advance.

**Comment by LewisVo** [comment]
Thank you for reporting @lmintmate . The developers of vocal definitely did some change to the repo (name change or change organization ... etc). I will update the correct link ;)
