### ISSUE TITLE
Add TeXworks to list under Office category

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#227]
TeXworks is yet another awesome (Xe)Latex editing software, and my personal favorite in fact. Its main difference with the others already on the list is that it aims to be easier for people who use TeX for the first time - it thus uses a simple interface, where a single button press can produce the desired pdf.
 Its homepage is found at [https://www.tug.org/texworks/](https://www.tug.org/texworks/), and its source code at [https://github.com/TeXworks/texworks](https://github.com/TeXworks/texworks). It was last updated on April 2017, which is reasonably recently. It can also be installed fairly easily -with a PPA in Ubuntu and via the AUR for Arch Linux. If you do decide to add it, here's how the entry could look like in the Markdown (this is just to add the description of TeXworks for the list):
`[TeXworks](https://www.tug.org/texworks/)Free cross-platform simple LaTeX editor, with the aim of lowering the entry barrier to the TeX world. [![Open-Source Software][OSS Icon]](https://github.com/TeXworks/texworks)`
Thanks in advance.

**Comment by LewisVo** [comment]
HI @lmintmate , first of all sorry for keep you waiting. It's national independence day in my country and I was off :smile: .  Yeah, about TeXworks, that's one good app. If you notice my github, you'll see another repo on Latex (I'm just proving that I can use Latex lol :rofl:) and I can see why TeXworks is your favorite. It's definitely worthy to be on the list. Thank you. :+1:
