### ISSUE TITLE
Agave's webpage isn't up anymore

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#228]
[The webpage of Agave](http://home.gna.org/colorscheme/) isn't up anymore, and the same goes with its parent domain home.gna.org. It appears that, according to [this wayback machine capture](https://web.archive.org/web/20170331170349/http://gna.org/), the whole website closed down, and it seems that Agave didn't get a new homepage before Gna's closing down. Thankfully, there is [a wayback machine capture](https://web.archive.org/web/20170327063642/http://home.gna.org/colorscheme/) available for Agave, dating from March 27th 2017, from which the downloading of the source code is possible just by clicking on the links to it. Agave is also still available in the packages of Ubuntu and Arch Linux. Given this, it is possible to just replace the previous link of Agave to the wayback machine one. If there is a better course of action than this, feel free to act on that one instead. Thanks in advance.

**Comment by LewisVo** [comment]
HI @lmintmate , thank you for notifiying me. This is clearly a case of #195. I have decided to remove agave. It has been discontinued for a long time and its function can easily be replaced with gpick. 
Thank you again for spotting what's not many people can do.
