### ISSUE TITLE
Add link to CopyQ OSS icon

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#233]
CopyQ is missing the link to its source code via the OSS icon. Its source code can be found at [https://github.com/hluk/CopyQ](https://github.com/hluk/CopyQ).

**Comment by LewisVo** [comment]
Thank you. :+1:

**Comment by LewisVo** [comment]
59dc1d3a4a48d3060b39dfc494112952c2a40af6
