### ISSUE TITLE
Several entries are duplicated in the wrong category

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#234]
More specifically, the Note Taking category in its present state includes several applications that are duplicates from other categories (which are the correct ones for those entries). These are (in alphabetical order):
-Plank (also in Dock category)
-Plotinus (also in Local Search category)
-Pomodone app (also in Time and Task category)
-Recent noti (also in Widget and Indicator category)
-Redshift (also in Miscellaneous category)
-Shots (also in Screenshot category)
-Shutter (also in Screenshot category)

These duplicate entries should be removed from the note taking category as to avoid causing any confusion. Thanks in advance for understanding.

**Comment by LewisVo** [comment]
Hi @lmintmate , it was definitely my bad when splitting up the category. I ll fix them all right now. thank you for notifying me. :+1:

**Comment by LewisVo** [comment]
These are all fixed in 59dc1d3a4a48d3060b39dfc494112952c2a40af6. thank you so much again. :+1:
