### ISSUE TITLE
Delegate/link audio section to github.com/nodiscc/awesome-linuxaudio ?

### ISSUE THREAD

**Issue by nodiscc** [LewisVo/Awesome-Linux-Software#235]
Hi, I noticed you are maintaining an `Audio` section at https://github.com/LewisVo/Awesome-Linux-Software#audio. I alsa maintain a list of Linux audio software at https://github.com/nodiscc/awesome-linuxaudio. It's currently in a good state except some dead links.

Would you like to delegate the audio section to my list, and link to it like [what is done on awesome-selfhosted](https://github.com/Kickball/awesome-selfhosted/#monitoring)? (ie. link to a more specialized awesome list)

I think this would prevent duplication of effort and help provide a more thorough and organized list.

I can take care of moving the Audio entries to my list if needed (most of them are already there). Currently awesome-linuxaudio has no direct "Source code" links, like this list does; I can add it as well if needed.

If you don't want to do that feel free to copy-paste from awesome-linuxaudio, It's under [CC-BY-SA 3.0](https://github.com/nodiscc/awesome-linuxaudio#license) license.

Cheers

**Comment by LewisVo** [comment]
Hi @nodiscc , I took a look at your work. It is great and invaluable, indeed. Also, thank you for your kind offer. I totally understand your idea and how it would benefit the community if I linked audio section to your list. Here's my opinion: 
1. I will not delete all apps inside the audio section. At least for now. I will consider that in the near future. Your list is awesome and well composed. However, it is somehow overwhelming and advanced (at least in my view). This is not to say that it's not good. I just want some time to think about this 😄 .
2. I will definitely put a link to your project at the top of the audio section, noting that users who have more complex usage or in need of a better Linux audio software list please visit your project. 
Does this sound good to you? I am willing to hear your feedback on this. Thanks 👍

**Comment by nodiscc** [comment]
Sounds good :) You are right, my list can be overwhelming - your audio section is really good and covers what most people would want to try (ardour, mixxx, hydrogen, quodlibet... all are nice) . A `see also` link at the end would be fine. :+1: https://github.com/nodiscc/awesome-linuxaudio/#other-software-lists now also links to here.

Yeah maintaining a concise/short list is hard. I've tried to use **bold** to highlight the major projects in each section, but it is really time consuming... having a separate, less advanced, condensed list is better in some aspects. Also check out https://github.com/kickball/awesome-selfhosted and https://github.com/n1trux/awesome-sysadmin if you're interested in more specialized but truly awesome Linux software.

Thanks everyone for your work

**Comment by LewisVo** [comment]
96cd94c
