### ISSUE TITLE
Muno isn't compatible with Linux

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#238]
Just noticed the recent addition of this application called Muno, which in its description states that it is for Mac. True enough, when I went to the [Muno site](http://munoapp.com/) from my pc running Linux Mint, the site had, in the place the download link would be, "Platform not supported" instead (and unclickable at that too). So this one should probably be removed since it isn't compatible with Linux, and thus has no place in this list with Linux-compatible software.

**Comment by LewisVo** [comment]
Hi @lmintmate , sorry for that and thank you for notifying me. Too many things have happened but if I remember it right, it's like 4 days ago I was able to download it myself since I have to run every app before adding to the list. Dont know what happened though...
