### ISSUE TITLE
Amend the name of asciinema

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#239]
Asciinema is reported on the list as ASCII Nema. This isn't the correct name, firstly because all the official places (the site and the github repo, for example) report the name as one word, Asciinema, and secondly, because the name is a play on the words ascii and cinema, and thus shouldn't be separated (Nema doesn't mean anything without the ci- part after all).
Thanks again in advance.

**Comment by LewisVo** [comment]
Thank you. I wasn't paying much attention to this.
