### ISSUE TITLE
Calibre-web

### ISSUE THREAD

**Issue by wuqi** [LewisVo/Awesome-Linux-Software#241]
[Calibre-web](https://github.com/janeczku/calibre-web)  providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database. 

The UI is much better than calibre

**Comment by LewisVo** [comment]
Thank you for your recommendation @wuqi , I would definitely try Calibre-web

**Comment by LewisVo** [comment]
7a19c8f
