### ISSUE TITLE
Fossil OSS link is at the wrong place

### ISSUE THREAD

**Issue by lmintmate** [LewisVo/Awesome-Linux-Software#250]
The link for the source files of Fossil isn't next to the OSS icon, the icon instead being an empty link and enclosed in brackets. It is placed instead next to the OSS icon of Fisherman (which is a correct entry otherwise, complete with the correct link on the OSS icon), enclosed in parentheses.

**Comment by LewisVo** [comment]
Thank you @lmintmate , one contributor messed that up and it is my fault not noticing that when reviewing PR. Fixed now
