### ISSUE TITLE
Question about paid but free for personal use programs

### ISSUE THREAD

**Issue by FabioLolix** [LewisVo/Awesome-Linux-Software#313]
There are at least 3 programs which are paid but free for personal,

* Gitkraken
* Smartgit
* Teamviewer

Guidelines for description and use of icons should be unified

**Comment by SaintFenix** [comment]
As far as I've gleaned in my time here, the icons are merely to show if an application is open source or not.

So the OSS Icon being for open source and free. (with optional paid for options, usually hosted by the software provider.)

Software with no OSS Icon, being for free as in beer.

The Paid Icon meaning only that the software is closed source, and paid for.

I don't doubt that we get a lot of views here, as we rank pretty high on Google, but I really do wonder if companies are referring to our list, and need a "this is a paid for you application, but not for an individual user." icon especially seeing as this list seems to present itself as a "for newbies" project.

**Comment by LewisVo** [comment]
@FabioLolix I understand your concern. My list uses no icon for programs that "are paid but free for personal". And I think that is clear and obvious enough for users.
